# Generated by Django 4.1.5 on 2023-01-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_teacher_his_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
