# Generated by Django 4.1.5 on 2023-02-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_courses_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studintinfo',
            name='his_course',
        ),
        migrations.AddField(
            model_name='studintinfo',
            name='his_course',
            field=models.ManyToManyField(to='student.courses'),
        ),
    ]
