# Generated by Django 4.1.5 on 2023-02-06 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studintinfo_his_course_studintinfo_his_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studintinfo',
            name='his_course',
        ),
        migrations.AddField(
            model_name='studintinfo',
            name='his_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.courses'),
            preserve_default=False,
        ),
    ]
